### ISSUE TITLE
Update ASP.NET docker container to new URI

### ISSUE THREAD

**Issue by RodneyRichardson** [fbarresi/SoftBeckhoff#3]
https://hub.docker.com/_/microsoft-dotnet-aspnet

Microsoft have moved/renamed their docker containers as part of .NET Core 5,0 release.

You should be able to rename the ASP.NET docker container used to the LTS version without any other changes: mcr.microsoft.com/dotnet/aspnet:3.1

**Comment by fbarresi** [comment]
Thank you for reporting it!
