### ISSUE TITLE
is this a working XAR of TwinCAT?

### ISSUE THREAD

**Issue by runtimevic** [fbarresi/SoftBeckhoff#7]
Hi @fbarresi ,
Is this SoftBeckhoff a TwinCAT XAR? 
I'm not sure what its functionality is for?
Best regards, Víctor.

**Comment by fbarresi** [comment]
Hi Víctor,

This is a test system that simulates a beckhoff in form of a docker container. I made it for allowing testing the communications with high level applications (for example within a ci/cd pipeline) that uses ads for gathering data from plcs.

I have another similar project for the usage of siemens plc: github.com/fbarresi/softplc

Best regards,
FB
